webtalk_init -webtalk_dir /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Dec 29 11:05:46 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "un80l9ammnb8k4v0vrbgpomnmv" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1577627809000" -context "sdk\\\\hardware/1577627809000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1577627809000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1577627809000"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4" -context "sdk\\\\hardware/1577627809000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1577627809000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1577627809000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1577627809000"
webtalk_add_data -client sdk -key uid -value "1577627867000" -context "sdk\\\\bsp/1577627867000"
webtalk_add_data -client sdk -key hwid -value "1577627809000" -context "sdk\\\\bsp/1577627867000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1577627867000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1577627867000"
webtalk_add_data -client sdk -key uid -value "1577627870000" -context "sdk\\\\application/1577627870000"
webtalk_add_data -client sdk -key hwid -value "1577627809000" -context "sdk\\\\application/1577627870000"
webtalk_add_data -client sdk -key bspid -value "1577627867000" -context "sdk\\\\application/1577627870000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1577627870000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1577627870000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1577627870000"
webtalk_transmit -clientid 3494147375 -regid "" -xml /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
