set_property SRC_FILE_INFO {cfile:/home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2018.2/exercise04/exercise04.srcs/constrs_1/new/pynq-z2_v1.0.xdc rfile:../../../exercise04.srcs/constrs_1/new/pynq-z2_v1.0.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14   [get_ports { LEDs_out[0] }]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14   [get_ports { LEDs_out[1] }]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16   [get_ports { LEDs_out[2] }]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14   [get_ports { LEDs_out[3] }]
