# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.cache/wt [current_project]
set_property parent.project_path /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/ip_repo/led_controller_1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/sources_1/bd/led_test_system/led_test_system.bd
set_property used_in_implementation false [get_files -all /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/sources_1/bd/led_test_system/ip/led_test_system_processing_system7_0_0/led_test_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/sources_1/bd/led_test_system/ip/led_test_system_rst_processing_system7_0_100M_0/led_test_system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/sources_1/bd/led_test_system/ip/led_test_system_rst_processing_system7_0_100M_0/led_test_system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/sources_1/bd/led_test_system/ip/led_test_system_rst_processing_system7_0_100M_0/led_test_system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/sources_1/bd/led_test_system/ip/led_test_system_auto_pc_0/led_test_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/sources_1/bd/led_test_system/led_test_system_ooc.xdc]
set_property is_locked true [get_files /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/sources_1/bd/led_test_system/led_test_system.bd]

read_vhdl -library xil_defaultlib /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/sources_1/bd/led_test_system/hdl/led_test_system_wrapper.vhd
read_xdc /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/constrs_1/new/pynq-z2_v1.0.xdc
set_property used_in_implementation false [get_files /home/carlos/Desktop/REPO/github/cpantel/TheZynqBook/pynq-z2/2015.4/Exercise04/Exercise04.srcs/constrs_1/new/pynq-z2_v1.0.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top led_test_system_wrapper -part xc7z020clg400-1
write_checkpoint -noxdef led_test_system_wrapper.dcp
catch { report_utilization -file led_test_system_wrapper_utilization_synth.rpt -pb led_test_system_wrapper_utilization_synth.pb }
