# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Exercise01b/Exercise01b.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exercise01b || ORIG_REF_NAME==Exercise01b}]

# IP: bd/Exercise01b/ip/Exercise01b_processing_system7_0_0/Exercise01b_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exercise01b_processing_system7_0_0 || ORIG_REF_NAME==Exercise01b_processing_system7_0_0}]

# IP: bd/Exercise01b/ip/Exercise01b_axi_gpio_0_0/Exercise01b_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exercise01b_axi_gpio_0_0 || ORIG_REF_NAME==Exercise01b_axi_gpio_0_0}]

# IP: bd/Exercise01b/ip/Exercise01b_processing_system7_0_axi_periph_2/Exercise01b_processing_system7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exercise01b_processing_system7_0_axi_periph_2 || ORIG_REF_NAME==Exercise01b_processing_system7_0_axi_periph_2}]

# IP: bd/Exercise01b/ip/Exercise01b_rst_processing_system7_0_100M_2/Exercise01b_rst_processing_system7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exercise01b_rst_processing_system7_0_100M_2 || ORIG_REF_NAME==Exercise01b_rst_processing_system7_0_100M_2}]

# IP: bd/Exercise01b/ip/Exercise01b_auto_pc_0/Exercise01b_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exercise01b_auto_pc_0 || ORIG_REF_NAME==Exercise01b_auto_pc_0}]

# XDC: bd/Exercise01b/ip/Exercise01b_processing_system7_0_0/Exercise01b_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Exercise01b_processing_system7_0_0 || ORIG_REF_NAME==Exercise01b_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/Exercise01b/ip/Exercise01b_axi_gpio_0_0/Exercise01b_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Exercise01b_axi_gpio_0_0 || ORIG_REF_NAME==Exercise01b_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Exercise01b/ip/Exercise01b_axi_gpio_0_0/Exercise01b_axi_gpio_0_0_ooc.xdc

# XDC: bd/Exercise01b/ip/Exercise01b_axi_gpio_0_0/Exercise01b_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Exercise01b_axi_gpio_0_0 || ORIG_REF_NAME==Exercise01b_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Exercise01b/ip/Exercise01b_rst_processing_system7_0_100M_2/Exercise01b_rst_processing_system7_0_100M_2_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exercise01b_rst_processing_system7_0_100M_2 || ORIG_REF_NAME==Exercise01b_rst_processing_system7_0_100M_2}]

# XDC: bd/Exercise01b/ip/Exercise01b_rst_processing_system7_0_100M_2/Exercise01b_rst_processing_system7_0_100M_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exercise01b_rst_processing_system7_0_100M_2 || ORIG_REF_NAME==Exercise01b_rst_processing_system7_0_100M_2}]

# XDC: bd/Exercise01b/ip/Exercise01b_rst_processing_system7_0_100M_2/Exercise01b_rst_processing_system7_0_100M_2_ooc.xdc

# XDC: bd/Exercise01b/ip/Exercise01b_auto_pc_0/Exercise01b_auto_pc_0_ooc.xdc

# XDC: bd/Exercise01b/Exercise01b_ooc.xdc
