// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_mult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_mult::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_mult::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> matrix_mult::ap_ST_fsm_state1 = "1";
const sc_lv<8> matrix_mult::ap_ST_fsm_state2 = "10";
const sc_lv<8> matrix_mult::ap_ST_fsm_state3 = "100";
const sc_lv<8> matrix_mult::ap_ST_fsm_state4 = "1000";
const sc_lv<8> matrix_mult::ap_ST_fsm_state5 = "10000";
const sc_lv<8> matrix_mult::ap_ST_fsm_state6 = "100000";
const sc_lv<8> matrix_mult::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> matrix_mult::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> matrix_mult::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrix_mult::ap_const_lv32_1 = "1";
const sc_lv<1> matrix_mult::ap_const_lv1_0 = "0";
const sc_lv<32> matrix_mult::ap_const_lv32_2 = "10";
const sc_lv<32> matrix_mult::ap_const_lv32_3 = "11";
const sc_lv<32> matrix_mult::ap_const_lv32_4 = "100";
const sc_lv<32> matrix_mult::ap_const_lv32_5 = "101";
const sc_lv<32> matrix_mult::ap_const_lv32_7 = "111";
const sc_lv<3> matrix_mult::ap_const_lv3_0 = "000";
const sc_lv<1> matrix_mult::ap_const_lv1_1 = "1";
const sc_lv<16> matrix_mult::ap_const_lv16_0 = "0000000000000000";
const sc_lv<3> matrix_mult::ap_const_lv3_5 = "101";
const sc_lv<3> matrix_mult::ap_const_lv3_1 = "1";
const sc_lv<2> matrix_mult::ap_const_lv2_0 = "00";
const bool matrix_mult::ap_const_boolean_1 = true;

matrix_mult::matrix_mult(sc_module_name name) : sc_module(name), mVcdFile(0) {
    matrix_mult_mac_mbkb_U1 = new matrix_mult_mac_mbkb<1,3,8,8,16,16>("matrix_mult_mac_mbkb_U1");
    matrix_mult_mac_mbkb_U1->clk(ap_clk);
    matrix_mult_mac_mbkb_U1->reset(ap_rst);
    matrix_mult_mac_mbkb_U1->din0(b_q0);
    matrix_mult_mac_mbkb_U1->din1(a_q0);
    matrix_mult_mac_mbkb_U1->din2(prod_load_reg_102);
    matrix_mult_mac_mbkb_U1->ce(ap_var_for_const0);
    matrix_mult_mac_mbkb_U1->dout(grp_fu_246_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_12_cast_fu_230_p1 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_126_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_126_p2 );

    SC_METHOD(thread_b_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_15_cast_fu_234_p1 );

    SC_METHOD(thread_b_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_exitcond1_fu_160_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_reg_91 );

    SC_METHOD(thread_exitcond2_fu_126_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_80 );

    SC_METHOD(thread_exitcond_fu_186_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( k_reg_115 );

    SC_METHOD(thread_i_1_fu_132_p2);
    sensitive << ( i_reg_80 );

    SC_METHOD(thread_j_1_fu_166_p2);
    sensitive << ( j_reg_91 );

    SC_METHOD(thread_k_1_fu_192_p2);
    sensitive << ( k_reg_115 );

    SC_METHOD(thread_p_shl1_cast_fu_215_p1);
    sensitive << ( tmp_10_fu_207_p3 );

    SC_METHOD(thread_p_shl_cast_fu_150_p1);
    sensitive << ( tmp_9_fu_142_p3 );

    SC_METHOD(thread_prod_address0);
    sensitive << ( prod_addr_reg_281 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_prod_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_prod_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( prod_load_reg_102 );

    SC_METHOD(thread_prod_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_tmp_10_fu_207_p3);
    sensitive << ( k_reg_115 );

    SC_METHOD(thread_tmp_11_cast_fu_181_p1);
    sensitive << ( tmp_2_fu_176_p2 );

    SC_METHOD(thread_tmp_11_fu_219_p2);
    sensitive << ( tmp_4_cast_fu_198_p1 );
    sensitive << ( p_shl1_cast_fu_215_p1 );

    SC_METHOD(thread_tmp_12_cast_fu_230_p1);
    sensitive << ( tmp_4_reg_294 );

    SC_METHOD(thread_tmp_12_fu_225_p2);
    sensitive << ( tmp_2_cast_reg_276 );
    sensitive << ( tmp_11_fu_219_p2 );

    SC_METHOD(thread_tmp_15_cast_fu_234_p1);
    sensitive << ( tmp_12_reg_299 );

    SC_METHOD(thread_tmp_2_cast_fu_172_p1);
    sensitive << ( j_reg_91 );

    SC_METHOD(thread_tmp_2_fu_176_p2);
    sensitive << ( tmp_s_reg_262 );
    sensitive << ( tmp_2_cast_fu_172_p1 );

    SC_METHOD(thread_tmp_4_cast_fu_198_p1);
    sensitive << ( k_reg_115 );

    SC_METHOD(thread_tmp_4_fu_202_p2);
    sensitive << ( tmp_s_reg_262 );
    sensitive << ( tmp_4_cast_fu_198_p1 );

    SC_METHOD(thread_tmp_9_fu_142_p3);
    sensitive << ( i_reg_80 );

    SC_METHOD(thread_tmp_cast_fu_138_p1);
    sensitive << ( i_reg_80 );

    SC_METHOD(thread_tmp_s_fu_154_p2);
    sensitive << ( tmp_cast_fu_138_p1 );
    sensitive << ( p_shl_cast_fu_150_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_fu_126_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond1_fu_160_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond_fu_186_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_mult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
    sc_trace(mVcdFile, b_address0, "(port)b_address0");
    sc_trace(mVcdFile, b_ce0, "(port)b_ce0");
    sc_trace(mVcdFile, b_q0, "(port)b_q0");
    sc_trace(mVcdFile, prod_address0, "(port)prod_address0");
    sc_trace(mVcdFile, prod_ce0, "(port)prod_ce0");
    sc_trace(mVcdFile, prod_we0, "(port)prod_we0");
    sc_trace(mVcdFile, prod_d0, "(port)prod_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_1_fu_132_p2, "i_1_fu_132_p2");
    sc_trace(mVcdFile, i_1_reg_257, "i_1_reg_257");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_s_fu_154_p2, "tmp_s_fu_154_p2");
    sc_trace(mVcdFile, tmp_s_reg_262, "tmp_s_reg_262");
    sc_trace(mVcdFile, exitcond2_fu_126_p2, "exitcond2_fu_126_p2");
    sc_trace(mVcdFile, j_1_fu_166_p2, "j_1_fu_166_p2");
    sc_trace(mVcdFile, j_1_reg_271, "j_1_reg_271");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_2_cast_fu_172_p1, "tmp_2_cast_fu_172_p1");
    sc_trace(mVcdFile, tmp_2_cast_reg_276, "tmp_2_cast_reg_276");
    sc_trace(mVcdFile, exitcond1_fu_160_p2, "exitcond1_fu_160_p2");
    sc_trace(mVcdFile, prod_addr_reg_281, "prod_addr_reg_281");
    sc_trace(mVcdFile, k_1_fu_192_p2, "k_1_fu_192_p2");
    sc_trace(mVcdFile, k_1_reg_289, "k_1_reg_289");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_4_fu_202_p2, "tmp_4_fu_202_p2");
    sc_trace(mVcdFile, tmp_4_reg_294, "tmp_4_reg_294");
    sc_trace(mVcdFile, exitcond_fu_186_p2, "exitcond_fu_186_p2");
    sc_trace(mVcdFile, tmp_12_fu_225_p2, "tmp_12_fu_225_p2");
    sc_trace(mVcdFile, tmp_12_reg_299, "tmp_12_reg_299");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_246_p3, "grp_fu_246_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, i_reg_80, "i_reg_80");
    sc_trace(mVcdFile, j_reg_91, "j_reg_91");
    sc_trace(mVcdFile, prod_load_reg_102, "prod_load_reg_102");
    sc_trace(mVcdFile, k_reg_115, "k_reg_115");
    sc_trace(mVcdFile, tmp_11_cast_fu_181_p1, "tmp_11_cast_fu_181_p1");
    sc_trace(mVcdFile, tmp_12_cast_fu_230_p1, "tmp_12_cast_fu_230_p1");
    sc_trace(mVcdFile, tmp_15_cast_fu_234_p1, "tmp_15_cast_fu_234_p1");
    sc_trace(mVcdFile, tmp_9_fu_142_p3, "tmp_9_fu_142_p3");
    sc_trace(mVcdFile, tmp_cast_fu_138_p1, "tmp_cast_fu_138_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_150_p1, "p_shl_cast_fu_150_p1");
    sc_trace(mVcdFile, tmp_2_fu_176_p2, "tmp_2_fu_176_p2");
    sc_trace(mVcdFile, tmp_4_cast_fu_198_p1, "tmp_4_cast_fu_198_p1");
    sc_trace(mVcdFile, tmp_10_fu_207_p3, "tmp_10_fu_207_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_215_p1, "p_shl1_cast_fu_215_p1");
    sc_trace(mVcdFile, tmp_11_fu_219_p2, "tmp_11_fu_219_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("matrix_mult.hdltvin.dat");
    mHdltvoutHandle.open("matrix_mult.hdltvout.dat");
}

matrix_mult::~matrix_mult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete matrix_mult_mac_mbkb_U1;
}

void matrix_mult::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void matrix_mult::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        i_reg_80 = i_1_reg_257.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_80 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_186_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        j_reg_91 = j_1_reg_271.read();
    } else if ((esl_seteq<1,1,1>(exitcond2_fu_126_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        j_reg_91 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        k_reg_115 = k_1_reg_289.read();
    } else if ((esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        k_reg_115 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        prod_load_reg_102 = grp_fu_246_p3.read();
    } else if ((esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        prod_load_reg_102 = ap_const_lv16_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_1_reg_257 = i_1_fu_132_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_1_reg_271 = j_1_fu_166_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        k_1_reg_289 = k_1_fu_192_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        prod_addr_reg_281 =  (sc_lv<5>) (tmp_11_cast_fu_181_p1.read());
        tmp_2_cast_reg_276 = tmp_2_cast_fu_172_p1.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_fu_186_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        tmp_12_reg_299 = tmp_12_fu_225_p2.read();
        tmp_4_reg_294 = tmp_4_fu_202_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_fu_126_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        tmp_s_reg_262 = tmp_s_fu_154_p2.read();
    }
}

void matrix_mult::thread_a_address0() {
    a_address0 =  (sc_lv<5>) (tmp_12_cast_fu_230_p1.read());
}

void matrix_mult::thread_a_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrix_mult::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void matrix_mult::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void matrix_mult::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void matrix_mult::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void matrix_mult::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void matrix_mult::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void matrix_mult::thread_ap_done() {
    if ((esl_seteq<1,1,1>(exitcond2_fu_126_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_mult::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_mult::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond2_fu_126_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_mult::thread_b_address0() {
    b_address0 =  (sc_lv<5>) (tmp_15_cast_fu_234_p1.read());
}

void matrix_mult::thread_b_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        b_ce0 = ap_const_logic_1;
    } else {
        b_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_exitcond1_fu_160_p2() {
    exitcond1_fu_160_p2 = (!j_reg_91.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_91.read() == ap_const_lv3_5);
}

void matrix_mult::thread_exitcond2_fu_126_p2() {
    exitcond2_fu_126_p2 = (!i_reg_80.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_80.read() == ap_const_lv3_5);
}

void matrix_mult::thread_exitcond_fu_186_p2() {
    exitcond_fu_186_p2 = (!k_reg_115.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_115.read() == ap_const_lv3_5);
}

void matrix_mult::thread_i_1_fu_132_p2() {
    i_1_fu_132_p2 = (!i_reg_80.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_reg_80.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void matrix_mult::thread_j_1_fu_166_p2() {
    j_1_fu_166_p2 = (!j_reg_91.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(j_reg_91.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void matrix_mult::thread_k_1_fu_192_p2() {
    k_1_fu_192_p2 = (!k_reg_115.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k_reg_115.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void matrix_mult::thread_p_shl1_cast_fu_215_p1() {
    p_shl1_cast_fu_215_p1 = esl_zext<6,5>(tmp_10_fu_207_p3.read());
}

void matrix_mult::thread_p_shl_cast_fu_150_p1() {
    p_shl_cast_fu_150_p1 = esl_zext<6,5>(tmp_9_fu_142_p3.read());
}

void matrix_mult::thread_prod_address0() {
    prod_address0 = prod_addr_reg_281.read();
}

void matrix_mult::thread_prod_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        prod_ce0 = ap_const_logic_1;
    } else {
        prod_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_prod_d0() {
    prod_d0 = prod_load_reg_102.read();
}

void matrix_mult::thread_prod_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        prod_we0 = ap_const_logic_1;
    } else {
        prod_we0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_tmp_10_fu_207_p3() {
    tmp_10_fu_207_p3 = esl_concat<3,2>(k_reg_115.read(), ap_const_lv2_0);
}

void matrix_mult::thread_tmp_11_cast_fu_181_p1() {
    tmp_11_cast_fu_181_p1 = esl_zext<64,6>(tmp_2_fu_176_p2.read());
}

void matrix_mult::thread_tmp_11_fu_219_p2() {
    tmp_11_fu_219_p2 = (!tmp_4_cast_fu_198_p1.read().is_01() || !p_shl1_cast_fu_215_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_4_cast_fu_198_p1.read()) + sc_biguint<6>(p_shl1_cast_fu_215_p1.read()));
}

void matrix_mult::thread_tmp_12_cast_fu_230_p1() {
    tmp_12_cast_fu_230_p1 = esl_zext<64,6>(tmp_4_reg_294.read());
}

void matrix_mult::thread_tmp_12_fu_225_p2() {
    tmp_12_fu_225_p2 = (!tmp_11_fu_219_p2.read().is_01() || !tmp_2_cast_reg_276.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_11_fu_219_p2.read()) + sc_biguint<6>(tmp_2_cast_reg_276.read()));
}

void matrix_mult::thread_tmp_15_cast_fu_234_p1() {
    tmp_15_cast_fu_234_p1 = esl_zext<64,6>(tmp_12_reg_299.read());
}

void matrix_mult::thread_tmp_2_cast_fu_172_p1() {
    tmp_2_cast_fu_172_p1 = esl_zext<6,3>(j_reg_91.read());
}

void matrix_mult::thread_tmp_2_fu_176_p2() {
    tmp_2_fu_176_p2 = (!tmp_s_reg_262.read().is_01() || !tmp_2_cast_fu_172_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_s_reg_262.read()) + sc_biguint<6>(tmp_2_cast_fu_172_p1.read()));
}

void matrix_mult::thread_tmp_4_cast_fu_198_p1() {
    tmp_4_cast_fu_198_p1 = esl_zext<6,3>(k_reg_115.read());
}

void matrix_mult::thread_tmp_4_fu_202_p2() {
    tmp_4_fu_202_p2 = (!tmp_s_reg_262.read().is_01() || !tmp_4_cast_fu_198_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_s_reg_262.read()) + sc_biguint<6>(tmp_4_cast_fu_198_p1.read()));
}

void matrix_mult::thread_tmp_9_fu_142_p3() {
    tmp_9_fu_142_p3 = esl_concat<3,2>(i_reg_80.read(), ap_const_lv2_0);
}

void matrix_mult::thread_tmp_cast_fu_138_p1() {
    tmp_cast_fu_138_p1 = esl_zext<6,3>(i_reg_80.read());
}

void matrix_mult::thread_tmp_s_fu_154_p2() {
    tmp_s_fu_154_p2 = (!tmp_cast_fu_138_p1.read().is_01() || !p_shl_cast_fu_150_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_cast_fu_138_p1.read()) + sc_biguint<6>(p_shl_cast_fu_150_p1.read()));
}

void matrix_mult::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond2_fu_126_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_186_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

void matrix_mult::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_address0\" :  \"" << a_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_ce0\" :  \"" << a_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a_q0\" :  \"" << a_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_address0\" :  \"" << b_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_ce0\" :  \"" << b_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b_q0\" :  \"" << b_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"prod_address0\" :  \"" << prod_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"prod_ce0\" :  \"" << prod_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"prod_we0\" :  \"" << prod_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"prod_d0\" :  \"" << prod_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

